# **Assignment For Numpy**

# Assignment By **Muhammad Faizan **
# Roll #         **PIAIC77687**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
x= np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [4]:
array_values = np.arange(10,50)
print(array_values)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [5]:
np.shape(array_values)

(40,)

5. Print the type of the previous array in question 3

In [6]:
type(array_values)

numpy.ndarray

6. Print the numpy version and the configuration


In [7]:
print(np.__version__)
print(np.show_config)

1.19.4
<function show at 0x7fbf3bdfb620>


7. Print the dimension of the array in question 3


In [8]:
array_values.ndim

1

8. Create a boolean array with all the True values

In [9]:
bool_arr = np.array([3,3], dtype=bool)

9. Create a two dimensional array




In [10]:
dd_array = np.array([[1,2,3],[1,2,3]])
print(dd_array)
print("This Dimensions of Array:")
dd_array.ndim

[[1 2 3]
 [1 2 3]]
This Dimensions of Array:


2

10. Create a three dimensional array



In [11]:
ddd_array = np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(ddd_array)
print("This Dimensions of Array:")
ddd_array.ndim

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
This Dimensions of Array:


3

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [12]:
np.arange(20, 0 , -1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [13]:
y = np.zeros(10)
print(y)
y[5] = 1
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [14]:
ddd_array = np.array([[[1,2,3],[1,2,3],[1,2,3]]])
ddd_array

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [15]:
arr = np.array([1, 2, 3, 4, 5])
float_arr = arr.astype(np.float64)
print(float_arr)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [17]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
compare = arr1 == arr2
new_array = compare.all()
print(new_array)

False


17. Extract all odd numbers from arr with values(0-9)

In [18]:
a = np.arange(0,9)
a[a % 2 == 1]

array([1, 3, 5, 7])

18. Replace all odd numbers to -1 from previous array

In [19]:
a = a-1
a

array([-1,  0,  1,  2,  3,  4,  5,  6,  7])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [20]:
arr = np.arange(10)
arr
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [21]:
a = np.ones([5,5])
print(a)
print("\n 1 on the border and 0 inside: \n")
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 1 on the border and 0 inside: 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [22]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
raveled_arr = arr2d.ravel()
raveled_arr[4]= 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [23]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [24]:
a = np.arange(9).reshape((3,3))
a[0]

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [25]:
b = np.arange(9).reshape(3,3)
b[1:2,1:2]

array([[4]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [26]:
c = np.arange(9).reshape(3,3)
print(c)
c[0:2,2]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([2, 5])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [27]:
x = np.random.random((10,10))
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Minimum and Maximum Values:
0.0013278407868351216 0.9926543236110446


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
print(c)

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.searchsorted(a, np.intersect1d(a, b))

array([1, 5])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
for name in names:
  if name!="Will":
    c = np.intersect1d(data,name)
    print(c)

[]
[]
[]
[]
[]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [31]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
for name in names:
  if name!="Will" and "Joe":
   c = np.intersect1d(name,data)
   print(c)

[]
[]
[]
[]
[]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [32]:
rand_arr = np.random.uniform(1,15, size=(5,3))
print(rand_arr)

[[11.0144782   9.58024798  3.45621754]
 [ 1.72327173  1.14731997 14.35189588]
 [ 5.14079249  4.30165971  2.12673816]
 [ 7.21760007  7.47386306  8.16648871]
 [ 7.75422804  8.60040391  9.18176174]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [33]:
rand_arr = np.random.uniform(1,16, size=(2,2,4))
print(rand_arr)

[[[ 3.81009243 11.70010651 13.23866391 11.62274835]
  [12.06526087  2.84787254  4.60420653  5.97475536]]

 [[14.90188694  4.96856836 12.56163144  5.38917593]
  [ 7.76807985  3.68389644  6.56615188 10.09063897]]]


33. Swap axes of the array you created in Question 32

In [34]:
rand_arr = np.random.uniform(1,16, size=(2,4,2))
print(rand_arr)

[[[ 8.10987154 15.52664139]
  [11.5933986   1.38612461]
  [13.98493184 14.62606537]
  [ 7.70229984 13.26352112]]

 [[13.0607278  11.52294931]
  [ 1.90050874 15.40956767]
  [13.37810332  7.66214565]
  [ 8.90015636  1.18947226]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [35]:
arr = np.arange(10)
for num in arr:
  sq_arr = np.sqrt(num)
  if sq_arr < 0.5:
    sq_arr = 0
  print(sq_arr)

0
1.0
1.4142135623730951
1.7320508075688772
2.0
2.23606797749979
2.449489742783178
2.6457513110645907
2.8284271247461903
3.0


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [36]:
a = np.random.randint(12, size=(12))
b = np.random.randint(12, size=(12))
c = np.maximum(a, b) 
print(c)

[ 3  7  7  7 11  9  7  8 11  7 10  8]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [37]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique_names = np.unique(names)
print(unique_names)

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [38]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a,b)
print(c)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [39]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
C = np.delete(sampleArray,0, 1)
newColumn = np.array([[10,10,10]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [40]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [41]:
a = np.random.randint(20, size=(20))
print(np.cumsum(a))

[  7   9   9  18  32  49  49  62  76  95 102 113 129 136 147 163 168 181
 199 213]
